name: Fork Merge Check

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  handle_fork_merge:
    if: ${{ github.event.pull_request.head.repo.fork == true }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: CheckoutPullRequest
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: BackupRunBot
        run: cp run_bot.py run_bot_backup.py

      - name: MergeFromBase
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git merge origin/${{ github.event.pull_request.base.ref }} --no-edit || true

      - name: RestoreRunBot
        run: cp run_bot_backup.py run_bot.py

      - name: CommitAndPush
        run: |
          git add run_bot.py
          git commit -m "Restore run_bot.py to original after merge"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
